project:
  type: website

website:
  title: "Geographic & Remote Job Market Analysis"
  page-navigation: true
  site-url: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Analysis"
        menu:
          - href: market_trends.qmd
            text: Market Trends / Geographic Analysis
          - href: modeling.qmd
            text: Data Cleaning & Modeling
          - href: AI.qmd
            text: Skill Analysis & Recommendations

format:
  html:
    theme: minty
    css: styles.css



