project:
  type: website

website:
  title: "Geographic and Remote Job Market Analysis-Group2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: geographic_analysis.ipynb
        text: geographic data analysis
      - href: market_trends.qmd
        text: Market Trends
      - href: skill_analysis.qmd
        text: Skill Analysis
      - href: career_strategy_recs.qmd
        text: Career Strategy Recommendations  





