project:
  type: website

website:
  title: "Geographic & Remote Job Market Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
        text: Menu
      -   href: market_trends.qmd
          text: Market Trends / Geographic Analysis
      -   href: skill_analysis.qmd
          text: Skill Analysis & Career Recommendations

format:
  html:
    theme: minty
    css: styles.css



