project:
  type: website

website:
  title: "Geographic & Remote Job Market Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: geographic_analysis.ipynb
        text: Geographic Data Analysis
      - href: market_trends.qmd
        text: Market Trends
      - href: skill_analysis.qmd
        text: Skill Analysis
      - href: career_strategy_recs.qmd
        text: Career Strategy Recommendations  

format:
  html:
    theme: minty
    css: styles.css



